name: Context Examples

on: ["push"]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        env:
          MY_ACTION: ${{ github.action }}
        run: echo "Hello World! $MY_ACTION"

