name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Display Event Data
        run: |
          echo "Full event data: ${{ toJson(github.event) }}"
          echo "Event type: ${{ github.event.action }}"
